baseurl = "https://hoangtranson.github.io/my-blog/"
title = "Hoang Tran Blog"
# theme = "hugo-creative-portfolio-theme-master"
theme = "cupper-hugo-theme-master"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "https-hoangtranson-github-io-my-blog"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-118292467-1"
publishDir = "docs"
  
[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "Frontend blog"
  copyright = "&copy;2018 Hoang Tran"
  sidebarAbout = [
    "I am a frontend developer with more than 3 years of experience.",
    "Originally from Gia Lai, currently based in Ho Chi Minh."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "hayden.tran.d@gmail.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  facebook      = "facebook.com/hayden.tran.2"
#   googleplus    = "full profile url in googleplus"
  email         = "hayden.tran.d@gmail.com"
#   twitter       = "full profile url in twitter"
  linkedin      = "https://www.linkedin.com/in/tran-hoang-150611103/"
  stackoverflow = "https://stackoverflow.com/users/4344732/hayden-tran"
#   instagram     = "full profile url in instagram"
  github        = "https://github.com/hoangtranson"